version: '3.5'
services:
  db:
    user: root
    image: postgres:17-alpine
    container_name: employees-db
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'employees'
    ports:
      - '5434:5432'
    expose:
      - 5432
#    volumes:
#      - db-data:/var/lib/postgresql/data
#
#volumes:
#  db-data:
#    driver: local