spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      authorizationserver:
        issuer: ${ISSUER_URI}
        client:
          cv-app-client:
            registration:
              client-id: ${CV_CLIENT_ID}
              client-secret: ${CV_CLIENT_SECRET}
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - ${CV_CLIENT_REDIRECT_URI}
              post-logout-redirect-uris:
                - ${CV_CLIENT_POST_LOGOUT_REDIRECT_URI}
              scopes:
                - openid
                - profile
                - microprofile-jwt
            require-authorization-consent: true

server:
  port: 9000
  servlet:
    session:
      cookie:
        name: AUTH_SERVER_SESSION_ID

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG