version: '3.5'
services:
  db:
    user: root
    image: postgres:17-alpine
    container_name: identity-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
    expose:
      - 5432