spring:
  application:
    name: CV-SERVICE
  data:
    mongodb:
      uri: ${DB_URL}
      database: ${DB_NAME}

mongock:
  migration-scan-package: org.k5va.repository.changelog

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}