server:
  port: 0

spring:
  application:
    name: CV-SERVICE
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: ${CONFIG_URI}
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      group-id: cv-request
      isolation-level: READ_COMMITTED
      auto-offset-reset: latest

app:
  kafka-topics:
    cv-topic:
      name: cv-topic
