spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:1234@localhost:8888

server:
  port: 0

logging:
  level:
    org.springframework.security: DEBUG
