spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5434/employees
    username: admin
    password: 1234
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka