spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: ${CONFIG_URI}

server:
  port: 0

logging:
  level:
    org.springframework.security: DEBUG
