spring:
  application:
    name: CV-CLIENT
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username
          spring:
            issuer-uri: ${SPRING_ISSUER_URI}
        registration:
          cv-app-keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            client-name: Keycloak
            scope:
              - openid
              - microprofile-jwt
          cv-app-spring:
            provider: spring
            client-id: ${SPRING_CLIENT_ID}
            client-secret: ${SPRING_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${AUTH_CODE_REDIRECT_URI}
            client-name: Spring authorization server
            scope:
              - openid
              - microprofile-jwt

server:
  port: 8090

cv:
  server:
    url: ${CV_SERVER_URL}

logging:
  level:
    org.k5va: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
