spring:
  application:
    name: CV-CLIENT
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
            user-name-attribute: preferred_username
          spring:
            issuer-uri: http://localhost:9000
        registration:
          cv-app-authorization-code:
            provider: keycloak
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-name: Keycloak
            scope:
              - openid
              - microprofile-jwt
          cv-app-authorization-code-2:
            provider: spring
            client-id: ${CLIENT_ID}
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8090/login/oauth2/code/cv-app-client"
            client-name: Spring authorization server
            scope:
              - openid
              - microprofile-jwt

server:
  port: 8090

cv:
  server:
    url: ${CV_SERVER_URL}

logging:
  level:
    org.k5va: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
